<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Carbon\Carbon;

class SeedChoicesData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $choices = [
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'在空载状态下，某汽车前轴重1000kg，后轴重2000kg，允许的最大载质量为3000kg。现采用路试法对其驻车制动性能进行检验，那么该车驻车制动装置应能保证车辆在坡度为__________道上正反两个方向上固定5min不动方为合格。（      ）',        
                'optiona'       =>'8%',
                'optionb'       =>'15%',
                'optionc'       =>'20%',
                'optiond'       =>'24%',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),    
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'某汽车最高设计车速为160km/h，其转向盘最大自由转动量的允许值为__________。（      ）',        
                'optiona'       =>'35°',
                'optionb'       =>'15°',
                'optionc'       =>'20°',
                'optiond'       =>'25°',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'转向节及臂。转向横直拉杆及球销在进行修理时，__________。（      ）',        
                'optiona'       =>'可以拼焊，球销不得过松',
                'optionb'       =>'不得拼焊，球销可以稍松',
                'optionc'       =>'不得拼焊，球销不得松旷',
                'optiond'       =>'可以拼焊，球销不得松旷',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'在进行汽车前照灯检测时，汽车应处于：__________。（      ）',        
                'optiona'       =>'电源系统处于充电状态',
                'optionb'       =>'发动机处于熄火状态',
                'optionc'       =>'电源系统处于放电状态',
                'optiond'       =>'任一种状态都可以',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'使用便携式制动性能测试仪检测，对皇冠V63.0ATRoyal进行路试制动性能检验，刚好满足制动时初速度是：__________。（      ）',        
                'optiona'       =>'20km/h',
                'optionb'       =>'30km/h',
                'optionc'       =>'40km/h',
                'optiond'       =>'50km/h',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'按GB21861-2014标准，对前照灯检验项目中，下列项目属于不检项的是：__________。（      ）',        
                'optiona'       =>'远光灯发光强度',
                'optionb'       =>'远近光灯垂直偏移',
                'optionc'       =>'远近光灯水平偏移',
                'optiond'       =>'以上都是',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'用平板检验台检测悬架特性时，驾驶员将车辆对正平板台，以__________速度驶上平板。（      ）',        
                'optiona'       =>'3～5km/h',
                'optionb'       =>'5～7km/h',
                'optionc'       =>'5～10km/h',
                'optiond'       =>'5～10km/h',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'用平板检验台检测悬架特性时，驾驶员将车辆对正平板台，以__________速度驶上平板。（      ）',        
                'optiona'       =>'3～5km/h',
                'optionb'       =>'5～7km/h',
                'optionc'       =>'5～10km/h',
                'optiond'       =>'5～10km/h',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'汽车整备质量不包含：__________。（      ）',        
                'optiona'       =>'冷却液',
                'optionb'       =>'燃料',
                'optionc'       =>'货物',
                'optiond'       =>'随车工具',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'机动车转向轮的胎冠花纹深度应大于等于__________；其余轮胎胎冠花纹深度应大于等于1.6mm。（      ）',        
                'optiona'       =>'2.8mm',
                'optionb'       =>'3.0mm',
                'optionc'       =>'3.2mm',
                'optiond'       =>'3.4mm',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'下列轮胎不应装用翻新的轮胎__________。（      ）',        
                'optiona'       =>'公路客车',
                'optionb'       =>'旅游客车',
                'optionc'       =>'校车',
                'optiond'       =>'以上都是',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'下列不应有闪烁情形的灯是__________。（      ）',        
                'optiona'       =>'转向信号灯',
                'optionb'       =>'危险警告灯',
                'optionc'       =>'紧急制动信号',
                'optiond'       =>'制动灯',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'下列部件不属于传动系统的是__________。（      ）',        
                'optiona'       =>'变速器',
                'optionb'       =>'传动轴',
                'optionc'       =>'万向节',
                'optiond'       =>'减振器',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'汽车使用平板式制动检验台进行检验时，最少检验时间为__________。（      ）',        
                'optiona'       =>'10s',
                'optionb'       =>'15s',
                'optionc'       =>'20s',
                'optiond'       =>'25s',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'底盘动态检验制动系时，应以不低于__________的速度正直行驶，双手轻抚方向盘，急踩制动踏板后迅速放松。（      ）',        
                'optiona'       =>'10km/h',
                'optionb'       =>'20km/h',
                'optionc'       =>'30km/h',
                'optiond'       =>'40km/h',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'下列说法正确的是__________。（      ）',        
                'optiona'       =>'机动车车身不允许喷涂或粘帖广告',
                'optionb'       =>'所有风窗玻璃不应张贴遮阳膜',
                'optionc'       =>'制动灯的发光强度应明显大于后位灯的发光强度',
                'optiond'       =>'转向信号灯的光色应为白色',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'下列说法不正确的是__________。（      ）',        
                'optiona'       =>'机动车车身外部不应有明显的镜面反射现象。',
                'optionb'       =>'校车和车长大于7.5m的其他客车不应设置有车外顶行李架。',
                'optionc'       =>'号牌架内侧边缘距离机动车登记编号字符边缘应大于6mm。',
                'optiond'       =>'校车应配备急救箱，急救箱应放置在便于取用的位置并且有效适用。',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'使汽车具有正常的操纵稳定性，车辆应具有适度的__________。（      ）',        
                'optiona'       =>'充分转向特性',
                'optionb'       =>'充足转向特性',
                'optionc'       =>'不足转向特性',
                'optiond'       =>'过足转向特性',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'在用机动车检验时，重中型货车、挂车的外廓尺寸应与机动车行驶证签注的内容相符，且误差不超过__________。（      ）',        
                'optiona'       =>'±1%或±50mm',
                'optionb'       =>'±2%或±100mm',
                'optionc'       =>'±3%或±150mm',
                'optiond'       =>'±5%或±200mm',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'注册登记检验时，机动车的轴距应与机动车产品公告、机动车出厂合格证相符，且误差不超过__________。（      ）',        
                'optiona'       =>'±1%或±50mm',
                'optionb'       =>'±2%或±100mm',
                'optionc'       =>'±3%或±150mm',
                'optiond'       =>'±5%或±200mm',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'注册登记检验时，货车、挂车的栏板高度应与机动车产品公告、机动车出厂合格证、驾驶室两侧喷涂的栏板高度数值相符，且误差不超过__________。（      ）',        
                'optiona'       =>'±1%或±50mm',
                'optionb'       =>'±2%或±100mm',
                'optionc'       =>'±3%或±150mm',
                'optiond'       =>'±5%或±200mm',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'以下哪种车辆应配备急救箱。（      ）',        
                'optiona'       =>'轿车',
                'optionb'       =>'货车',
                'optionc'       =>'警车',
                'optiond'       =>'校车',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'对于使用年限在10年以上的非营运小型、微型载客汽车，在送检时要增加__________等人工检验项目。（      ）',        
                'optiona'       =>'安全装置检查',
                'optionb'       =>'底盘动态检验和车辆底盘部件检查',
                'optionc'       =>'车辆特征参数检查',
                'optiond'       =>'底盘动态检验',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'转向信号灯的光色应为__________。（      ）',        
                'optiona'       =>'琥珀色',
                'optionb'       =>'莹白色',
                'optionc'       =>'红色',
                'optiond'       =>'粉红色',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'总质量大于等于__________的货车（半挂牵引车除外）、挂车，其车身（车厢）后部应喷涂/粘贴有符合规定的放大号，无法喷涂/粘贴的平板挂车应设置有符合规定的放大号。（      ）',        
                'optiona'       =>'3500kg',
                'optionb'       =>'4500kg',
                'optionc'       =>'9500kg',
                'optiond'       =>'12000kg',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'3',
                'title'         =>'采用密闭钢化玻璃式应急窗的__________，在相应的应急窗邻近应配备一个应急锤以方便击碎车窗玻璃。（      ）',        
                'optiona'       =>'客车',
                'optionb'       =>'轿车',
                'optionc'       =>'教练车',
                'optiond'       =>'警车',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'汽车排气管排放的气体污染物，通常指的是__________。（      ）',        
                'optiona'       =>'一氧化碳、碳氢化合物、氮氧化物',
                'optionb'       =>'二氧化碳、碳氢化合物、氮氧化物 ',
                'optionc'       =>'一氧化碳、碳氢化合物、氢氧化物',
                'optiond'       =>'二氧化碳、碳氢化合物、氢氧化物',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'对于低速货车的排气烟度只能使用__________标准来检测。（      ）',        
                'optiona'       =>'GB18322-2002',
                'optionb'       =>'GB18285-2005',
                'optionc'       =>'DB37/657-2011',
                'optiond'       =>'GB3847-2005',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'双怠速法检测所依据的标准是__________。（      ）',        
                'optiona'       =>'GB18322-2002',
                'optionb'       =>'GB18285-2005',
                'optionc'       =>'DB37/657-2011',
                'optiond'       =>'GB3847-2005',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'采用简易瞬态工况法时，其取样探头长度应至少为400mm，可插入车辆排气管深度至少应为__________mm。（      ）',        
                'optiona'       =>'200mm',
                'optionb'       =>'400mm',
                'optionc'       =>'250mm',
                'optiond'       =>'300mm',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'无论使用何种燃料，如果过量空气系数__________，则说明可燃混合气较稀。（      ）',        
                'optiona'       =>'λ=1',
                'optionb'       =>'λ<1',
                'optionc'       =>'λ>1 ',
                'optiond'       =>'λ≈1',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'高怠速工况是指用油门踏板将发动机转速稳定控制在__________额定转速。（      ）',        
                'optiona'       =>'30%',
                'optionb'       =>'50%',
                'optionc'       =>'70%',
                'optiond'       =>'80%',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'CO 与CO2 浓度之和小于__________,应终止排气检测,排放测量无效。（      ）',        
                'optiona'       =>'2%',
                'optionb'       =>'3%',
                'optionc'       =>'6%',
                'optiond'       =>'8%',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'重型汽车是指最大总质量超过__________kg的车辆。（      ）',        
                'optiona'       =>'1500',
                'optionb'       =>'2500',
                'optionc'       =>'3000',
                'optiond'       =>'3500',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'2001年10月1日前生产的柴油车应当采用__________测量排气烟度。（      ）',        
                'optiona'       =>'滤纸烟度法',
                'optionb'       =>'不透光烟度法',
                'optionc'       =>'双怠速法',
                'optiond'       =>'简易瞬态工况法',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'双怠速法对排放气体测试仪器技术条件规定CO、HC的测量应当采用__________。（      ）',        
                'optiona'       =>'不分光红外线法',
                'optionb'       =>'电化学电池法',
                'optionc'       =>'气相色谱法',
                'optiond'       =>'火焰离子法',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'尾气分析仪取样探头所用材料应能耐受的排气温度__________。（      ）',        
                'optiona'       =>'600℃',
                'optionb'       =>'500℃',
                'optionc'       =>'400℃',
                'optiond'       =>'300℃',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'底盘测功机最大测试车速不低于__________km/h。（      ）',        
                'optiona'       =>'100 km/h',
                'optionb'       =>'110 km/h',
                'optionc'       =>'120 km/h',
                'optiond'       =>'130 km/h',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'底盘测功机最大测试车速不低于__________km/h。（      ）',        
                'optiona'       =>'100 km/h',
                'optionb'       =>'110 km/h',
                'optionc'       =>'120 km/h',
                'optiond'       =>'130 km/h',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'五气分析仪的采样频率至少应为__________Hz。（      ）',        
                'optiona'       =>'1',
                'optionb'       =>'2',
                'optionc'       =>'4',
                'optiond'       =>'8',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'五气分析仪通电至预热结束指示出现所用的时间为__________min。（      ）',        
                'optiona'       =>'10',
                'optionb'       =>'20',
                'optionc'       =>'30',
                'optiond'       =>'40',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'“简易瞬态工况法”所使用的五气分析的温度范围：分析系统及相关部件应在__________。（      ）',        
                'optiona'       =>'0～40℃',
                'optionb'       =>'0～50℃',
                'optionc'       =>'0～60℃',
                'optiond'       =>'-10～40℃',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'不透光烟度计的光通道有效长度一般应为__________mm。（      ）',        
                'optiona'       =>'300',
                'optionb'       =>'350',
                'optionc'       =>'400',
                'optiond'       =>'430',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'双怠速检测中 油温应控制在__________之上。（      ）',        
                'optiona'       =>'60℃',
                'optionb'       =>'70℃',
                'optionc'       =>'80℃',
                'optiond'       =>'90℃',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'柴油车检测时，至少采取__________自由加速过程或其它等效方法对排气系统的杂质进行吹拂，保证排气管没有残留颗粒物。（      ）',        
                'optiona'       =>'1 次',
                'optionb'       =>'2 次',
                'optionc'       =>'3 次',
                'optiond'       =>'不用吹拂',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'柴油车检测时，至少采取__________自由加速过程或其它等效方法对排气系统的杂质进行吹拂，保证排气管没有残留颗粒物。（      ）',        
                'optiona'       =>'1 次',
                'optionb'       =>'2 次',
                'optionc'       =>'3 次',
                'optiond'       =>'不用吹拂',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'在用汽车自由加速试验不透光烟度法计算结果取最后__________次自由加速测量结果的算术平均值。（      ）',        
                'optiona'       =>'6',
                'optionb'       =>'4',
                'optionc'       =>'3',
                'optiond'       =>'2',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'2',
                'title'         =>'在进行自由加速测量时，必须在__________秒内，将油门踏板快速、连续地完全踩到底，使喷油泵在最短时间内供给最大油量。（      ）',        
                'optiona'       =>'1',
                'optionb'       =>'2',
                'optionc'       =>'3',
                'optiond'       =>'4',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构的授权签字人不能正常在岗时，其代理人的设置应为__________。（）',        
                'optiona'       =>'最高管理者',
                'optionb'       =>'技术负责人',
                'optionc'       =>'质量负责人',
                'optiond'       =>'不能设置',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],

            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构应由熟悉检验检测目的、程序、方法和结果评价的人员，对检验检测人员包括实习员工__________。（      ）',        
                'optiona'       =>'进行培训',
                'optionb'       =>'持续教育',
                'optionc'       =>'进行监督',
                'optiond'       =>'进行确认',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],

            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'设备在投入使用前，应采用__________等方式,以确认其是否满足检验检测的要求，并标识其状态。（      ）',        
                'optiona'       =>'设备比对',
                'optionb'       =>'标准物质',
                'optionc'       =>'检定或校准',
                'optiond'       =>'期间核查',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],

            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'技术负责人应具有中级及以上相关专业技术职称或者同等能力，大学专科毕业，从事相关专业检验检测活动__________年及以上。（      ）',        
                'optiona'       =>'6',
                'optionb'       =>'7',
                'optionc'       =>'8',
                'optiond'       =>'9',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构对其签发报告或证书的职责和范围应有__________。（      ）',        
                'optiona'       =>'设置代理人',
                'optionb'       =>'正式授权',
                'optionc'       =>'不授权',
                'optiond'       =>'不设代理人',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构对其签发报告或证书的职责和范围应有__________。（      ）',        
                'optiona'       =>'设置代理人',
                'optionb'       =>'正式授权',
                'optionc'       =>'不授权',
                'optiond'       =>'不设代理人',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'依据《检验检测机构资质认定评审准则》，以下属于质量记录的是__________。（      ）',        
                'optiona'       =>'样品管理记录',
                'optionb'       =>'合同评审记录',
                'optionc'       =>'人员培训考核记录',
                'optiond'       =>'环境条件控制记录',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'依据《检验检测机构资质认定评审准则》，下列检测活动属于不符合的有__________。（      ）',        
                'optiona'       =>'采用非标准检测方法',
                'optionb'       =>'经客户同意的方法偏离',
                'optionc'       =>'不满足体系文件要求',
                'optiond'       =>'租赁设备开展检测活动',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'依据《检验检测机构资质认定评审准则》的有关规定，__________需经国家或省级技术监督部门批准。（      ）',        
                'optiona'       =>'最高管理者',
                'optionb'       =>'技术负责人',
                'optionc'       =>'质量负责人',
                'optiond'       =>'授权签字人',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构应通过实施__________，应用审核结果、数据分析等来改进管理体系。（      ）',        
                'optiona'       =>'最高管理者',
                'optionb'       =>'技术负责人',
                'optionc'       =>'质量负责人',
                'optiond'       =>'授权签字人',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构质量手册的现行有效性由检验检测机构的__________负责保持。（      ）',        
                'optiona'       =>'最高管理者',
                'optionb'       =>'技术负责人',
                'optionc'       =>'质量负责人',
                'optiond'       =>'内审员',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'管理评审的目的是__________。（      ）',        
                'optiona'       =>'评价环境管理体系的符合性和有效性',
                'optionb'       =>'评价环境行为的符合性',
                'optionc'       =>'评价环境管理体系持续的适宜性、充分性和有效性',
                'optiond'       =>'评价环境管理体系的绩效',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构记录制度中的如下内容不正确的是__________。（      ）',        
                'optiona'       =>'记录应按照适当程序规范进行',
                'optionb'       =>'修改后的记录应重抄后存档',
                'optionc'       =>'规定了原始记录的保存期限',
                'optiond'       =>'保存记录应防止虫蛀',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构在确认了不符合工作时，应采取__________。（      ）',        
                'optiona'       =>'纠正措施',
                'optionb'       =>'预防措施',
                'optionc'       =>'纠正和预防措施',
                'optiond'       =>'合同评审',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'编写“申诉和投诉处理程序”，主要目的是__________。（      ）',        
                'optiona'       =>'满足客户的所有要求',
                'optionb'       =>'处理供应商对检验检测机构的不满',
                'optionc'       =>'满足客户的各种要求',
                'optiond'       =>'正确处理相关方意见，不断改善质量体系工作',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'质量手册是管理体系中最重要的文件，是管理体系文件的顶层文件。质量手册对检验检测机构内部是实施管理的纲领性文件，对外是证实检验检测机构管理体系符合标准要求的__________。（      ）',        
                'optiona'       =>'证据',
                'optionb'       =>'记录',
                'optionc'       =>'依据',
                'optiond'       =>'痕迹',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构应建立和保持选择和购买对检验检测质量有影响的服务和供应品的程序。明确服务、供应品、试剂、消耗材料的__________的要求，并保存对供应商的评价记录和合格供应商名单。（      ）',        
                'optiona'       =>'购买、验收、存储',
                'optionb'       =>'选择、验收、检验',
                'optionc'       =>'选择、验收、储存',
                'optiond'       =>'购买、验收、检验',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'仪器设备是否满足检测要求的依据是__________。（      ）',        
                'optiona'       =>'评审准则',
                'optionb'       =>'标准规范',
                'optionc'       =>'作业指导书',
                'optiond'       =>'质量手册',
                'answer'        =>' B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构应有质量控制程序和质量控制计划，以监控检测结果的__________。（      ）',        
                'optiona'       =>'可靠性',
                'optionb'       =>'有效性',
                'optionc'       =>'真实性',
                'optiond'       =>'合法性',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'每次检测或校准的记录应包括足够的信息以保证其能够__________。（      ）',        
                'optiona'       =>'满足要求',
                'optionb'       =>'充分有效',
                'optionc'       =>'再现',
                'optiond'       =>'真实可靠',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构应保留技术人员的相关资格、能力确认、授权、教育、培训和监督的记录，并包含授权和能力确认的__________。（      ）',        
                'optiona'       =>'项目',
                'optionb'       =>'日期',
                'optionc'       =>'资格',
                'optiond'       =>'方法',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测标准或者技术规范对环境条件有要求时或环境条件影响检验检测__________时，应监测、控制和记录环境条件。（      ）',        
                'optiona'       =>'结果',
                'optionb'       =>'设备',
                'optionc'       =>'状态',
                'optiond'       =>'方法',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构应建立和保持__________程序，定期参加能力验证或机构之间比对。（      ）',        
                'optiona'       =>'样品管理',
                'optionb'       =>'人员培训',
                'optionc'       =>'质量控制',
                'optiond'       =>'期间核查',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'1',
                'title'         =>'检验检测机构内部审核的目的是__________。（      ）',        
                'optiona'       =>'评价检验检测机构是否持续地按管理体系的要求运行',
                'optionb'       =>'改进和完善管理体系',
                'optionc'       =>'对管理评审的补充和完善',
                'optiond'       =>'得出管理体系的相应变更或改A进措施予以实施',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'4',
                'title'         =>'道路运输车辆技术等级划分为__________。（      ）',        
                'optiona'       =>'一级和二级',
                'optionb'       =>'一级、二级和三级',
                'optionc'       =>'合格、不合格',
                'optiond'       =>'以上答案都不对',
                'answer'        =>'A',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'4',
                'title'         =>'在用道路运输车辆检验时，__________的外廓尺寸、货车及挂车车箱栏板高度以及客车的实际座（铺）位数，检查是否与行驶证、机动车登记证、道路运输证记载的内容及其它相关资料相符。（      ）',        
                'optiona'       =>'重型货车',
                'optionb'       =>'重中型货车、专项作业车',
                'optionc'       =>'重中型货车及挂车',
                'optiond'       =>'所有车辆',
                'answer'        =>'C',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'4',
                'title'         =>'道路运输车辆需要检视__________是否装用翻新的轮胎。（      ）',        
                'optiona'       =>'客车和危险货物运输车所有车轮，其他不作要求',
                'optionb'       =>'客车和危险货物运输车的所有车轮、货车的转向轮',
                'optionc'       =>'所有道路运输车辆的转向车轮，其他不作要求',
                'optiond'       =>'以上答案都不正确',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'4',
                'title'         =>'悬架特性采用下列哪种仪器设备检验__________。（      ）',        
                'optiona'       =>'前轮定位仪',
                'optionb'       =>'底盘间隙仪',
                'optionc'       =>'便携式制动仪',
                'optiond'       =>'悬架检验台',
                'answer'        =>'D',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'category_id'   =>'4',
                'title'         =>'注册日期在三个月以内的车辆（按机动车行驶证的注册日期核定），动力性视为__________。（      ）',        
                'optiona'       =>'一级',
                'optionb'       =>'二级',
                'optionc'       =>'三级',
                'optiond'       =>'不做评定',
                'answer'        =>'B',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
        ];

        DB::table('choices')->insert($choices);
    }

    public function down()
    {
        DB::table('choices')->truncate();
    }
}
