<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Carbon\Carbon;
class SeedBlanksData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $blanks = [
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'在用机动车检验时，重中型货车、挂车的外廓尺寸应与机动车行驶证签注的内容相符，且误差不超______________或______________。',       
                'answer'        =>'±2% | ±100mm',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'机动车的整备质量误差满足重中型货车、挂车、专项作业车不超过______________或______________。',       
                'answer'        =>'±3% | ±500kg',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'在用车台试检验制动力平衡时，要求当轴制动力大于等于该轴轴荷60%时，后轴应______________，制动力小于该轴轴荷 60%时，后轴应______________。',       
                'answer'        =>'≤30% | ≤10%',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'____________________________、___________________________________应测试加载轴制动率和加载轴制动不平衡率。',       
                'answer'        =>'三轴及三轴以上的货车 | 采用并装双轴及并装三轴的挂车',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'铰接客车、铰接无轨电车、汽车列车行车制动空载整车制动率______________。',       
                'answer'        =>' ≥55% ',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'对车宽大于2.55m的汽车和汽车列车进行路试制动性能检验时，其试验通道宽度为______________。',       
                'answer'        =>'车宽(m)+0.5',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'在空载车状态下，汽车、摩托车前照灯近光光束照射在距离10m的屏幕上，近光光束明暗截止线转角或中点的垂直方向位置，对近光光束透光面中心（基准中心，下同）高度小于等于1000mm的机动车，应不高于近光光束透光面中心所在水平面以下 ______________的直线且不低于近光光束透光面中心所在水平面以下______________的直线；对近光光束透光面中心高度大于1000mm的机动车，应不高于近光光束 透光面中心所在水平面以下______________的直线且不低于近光光束透光面中心所在水平面以下______________的直线。',       
                'answer'        =>'50mm | 100m | 100mm | 350mm',
                'amount'        =>'4',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'3',
                'title'         =>'滚筒反力式制动检验台的第三滚筒的作用是________________、____________________，____________________________。',       
                'answer'        =>'测取车轮转速 | 计算滑移率 | 防止滚筒剥伤轮胎和保护驱动电机',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'GB18285-2005 规定，轻型汽车的高怠速转速为_______________，重型车的高怠速转速为_______________。',       
                'answer'        =>'2500±100r/min | 1800±100r/min',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'对于使用________________________和________________________的汽车进行过量空气系数 λ 的测定。',       
                'answer'        =>'闭环控制电子燃油喷射系统 | 三元催化转化器技术',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'GB18285-2005 规定，轻型汽车的高怠速转速为_______________，重型车的高怠速转速为_______________。',       
                'answer'        =>'2500±100r/min | 1800±100r/min',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'简易瞬态工况采样系统及相关部件的操作湿度范围为_______________。',       
                'answer'        =>'0% ~ 85%',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'GB18285-2005 规定，过量空气系数λ应在_______________或制造厂规定的范围内',       
                'answer'        =>'1.00±0.03',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'点燃式发动机汽车简易瞬态工况污染物排放试验设备包括：_______________、_______________和_______________组成的采样分析系统。',       
                'answer'        =>'底盘测功机 | 五气分析仪 | 气体流量分析仪',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'简易瞬态工况法测试期间有效行驶时间为_____________，理论行驶距离为_____________。',       
                'answer'        =>'195s | 1.013km',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ], 
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'第一类轻型汽车是指设计成员数不超过________人（包括司机），且最大总质量小于或等于_____________的M1类车',       
                'answer'        =>'底盘测功机 | 五气分析仪 | 气体流量分析仪',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ], 
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'点燃式发动机汽车简易瞬态工况污染物排放试验设备包括：_______________、_______________和_______________组成的采样分析系统。',       
                'answer'        =>'底盘测功机 | 五气分析仪 | 气体流量分析仪',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],  
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'当量惯量指在底盘测功机上用惯量模拟器模拟汽车行驶中_____________和_____________惯量时所相当的质量。',       
                'answer'        =>'移动 | 转动',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'基准质量（RM）是指整车整备质量加_____________质量。',       
                'answer'        =>'100kg',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ], 
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'适用于简易瞬态工况法检测的汽油车有___________________、____________________和______________________的车辆 。',       
                'answer'        =>'3.5吨以下的轻型在用车 | 且不具有全时四驱 | 具有驱动防滑功能但能关闭  ',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ], 
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'出厂日期2001年10月1日的第二类轻型汽车，整备质量为1160kg，该车利用简易瞬态工况法进行检测的排放限值CO为_____________、HC+NOx为_____________。',       
                'answer'        =>'12.0% | 2.9 10-6  ',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'2001年10月1日起生产的第二类轻型汽车，在进行双怠速检测时的限值为：怠速CO为_____________，HC为_____________，高怠速 CO为_____________，HC为_____________。',       
                'answer'        =>' 1.0% | 200 10-6 | 0.5% | 150 10-6  ',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'2',
                'title'         =>'当试验场地的环境温度超过_____________℃时，应开启直吹车辆散热器的冷却风机。',       
                'answer'        =>'22',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'你机构的质量（管理）手册的编写依据是：_________________________________________________________________。',       
                'answer'        =>'检验检测机构资质认定评审准则 及评审补充要求',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'管理体系文件主要有________________、________________、_________________ 和 _______________________组成。',       
                'answer'        =>'质量手册 | 程序文件 | 作业指导书 | 记录和表格或质量记录',
                'amount'        =>'4',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测原始记录、报告、证书的保存期限不少于__________年。',       
                'answer'        =>'6',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构_________________应当符合资质认定评审准则规定的能力要求，对外签发检验报告。',       
                'answer'        =>'授权签字人',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'授权签字人是由_____________________提名，经_____________________考核合格后，在其资质认定授权的_____________________签发检验检测报告或证书的人员。',       
                'answer'        =>'检验检测机构 | 资质认定部门 | 能力范围内',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构或者其所在的组织应有明确的法律地位，对其出具的检验检测___________、___________负责，并承担相应法律责任。不具备独立法人资格的检验检测机构应经所在法人单位授权。',       
                'answer'        =>'数据 | 结果',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构及其人员从事检验检测活动，应遵守国家相关法律法规的规定，遵循_____________、_____________、_____________原则，恪守职业道德，承担社会责任。',       
                'answer'        =>'客观独立 | 公平公正 | 诚实信用',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测标准或者技术规范对环境条件有要求时或环境条件影响检验检测结果时，应___________、___________和___________环境条件。当环境条件不利于检验检测的开展时，应停止检验检测活动。',       
                'answer'        =>'监测 | 控制 | 记录',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应建立和保持检验检测方法控制程序。检验检测方法包括________________、________________。应优先使用________________，并确保使用标准的有效版本。',       
                'answer'        =>'标准方法 | 非标准方法 | 标准方法',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>' 检验检测机构应建立和保持管理评审的程序。管理评审通常___________一次，由_________________负责。',       
                'answer'        =>'十二个月 | 最高管理者',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应建立和保持管理体系内部审核的程序，以便验证其运作是否符合管理体系和本准则的要求，管理体系是否得到有效的实施和保持。内部审核通常___________一次，由_________________策划内审并制定审核方案。',       
                'answer'        =>'每年 | 质量负责人',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应建立和保持在识别出不符合时，采取纠正措施的程序；当发现潜在不符合时，应采取预防措施。检验检测机构应通过实施质量方针、质量目标，应用审核结果、数据分析、纠正措施、预防措施、管理评审来持续改进管理体系的___________、___________和___________。',       
                'answer'        =>'适应性 | 充分性 | 有效性',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>' 检验检测机构应建立和保持评审客户要求、标书、合同的程序。对要求、标书、合同的偏离、变更应征得______________并通知相关人员。',       
                'answer'        =>'客户同意',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应建立和保持控制其管理体系的内部和外部文件的程序，明确文件的批准、发布、标识、变更和废止，防止使用___________、___________的文件。',       
                'answer'        =>'无效 | 作废',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应阐明质量方针，应制定质量目标，并在________________时予以评审。',       
                'answer'        =>'管理评审',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'具有并有效运行保证其检验检测活动___________、___________、___________、___________的管理体系。',       
                'answer'        =>'独立 | 公正 | 科学 | 诚信',
                'amount'        =>'4',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应建立和保持人员培训程序，确定人员的教育和培训目标，明确培训需求和实施人员培训，并评价这些培训活动的_______________。培训计划应适应检验检测机构当前和预期的任务。',       
                'answer'        =>'有效性',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>' 检验检测机构应对抽样、操作设备、检验检测、签发检验检测报告或证书以及提出意见和解释的人员，依据相应的教育、培训、技能和经验进行能力确认并持证上岗。应由熟悉检验检测目的、程序、方法和结果评价的人员，对检验检测人员包括实习员工_________________。',       
                'answer'        =>'进行监督',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'4检验检测机构的授权签字人应具有中级及以上相关专业技术职称或同等能力，并经___________________批准。非授权签字人不得签发检验检测报告或证书。',       
                'answer'        =>'资质认定部门',
                'amount'        =>'1',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'1',
                'title'         =>'检验检测机构应建立和保持维护其公正和诚信的程序。检验检测机构及其人员应不受来自内外部的、不正当的商业、财务和其他方面的压力和影响，确保检验检测数据、结果的___________、___________、___________和___________。',       
                'answer'        =>'真实 | 客观 | 准确 | 可追溯',
                'amount'        =>'4',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'4',
                'title'         =>'在用道路运输车辆综合性能检验分为“人工检验”和“性能检验”。人工检验项目中，标记“★”的项目为一般项，标记“■”的项目为关键项。性能检验项目中， ___________________、___________________为一般项，___________________不参与评价，其他项目为关键项。',       
                'answer'        => '车速表示值误差 | 前照灯光束垂直偏移 | 前照灯光束水平偏移',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'4',
                'title'         =>'人工检验项目及性能检验项目中，“关键项”的检验结果为合格且“一般项”的不合格项数不超过_________项时，检验结果判定为合格。',       
                'answer'        =>'6',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'4',
                'title'         =>'对于装用压燃式发动机车辆,动力性不合格时，调修后复检动力性、________________和______________；燃料经济性不合格时，调修后复检燃料经济性和______________；排放性不合格时，调修后复检排放性和______________。',       
                'answer'        =>'燃料经济性 | 排放性 | 动力性 | 动力性',
                'amount'        =>'4',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'4',
                'title'         =>'轴制动率不合格时，调修后复检轴制动率、________________和________________，并重新计算________________。',       
                'answer'        =>'制动不平衡率 | 同轴车轮阻滞率 | 整车制动率',
                'amount'        =>'3',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
            [
                'user_id'       =>'1',
                'bcategory_id'  =>'4',
                'title'         =>'根据技术评定要求，最高设计车速大于或等于100km/h的车辆，转向盘最大自由转动量不大于____________，其他车辆不大于____________为一级。',       
                'answer'        =>'10° | 20°',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
             [
                'user_id'       =>'1',
                'bcategory_id'  =>'4',
                'title'         =>'设计车速不小于100km/h，轴质量不大于1500kg的载客汽车,其轮胎在激励振动条件下测得的悬架吸收率应不小于____________，同轴左、右轮悬架吸收率之差不得大于____________。',       
                'answer'        =>'40% | 15%',
                'amount'        =>'2',
                'created_at'    =>Carbon::now()->toDateTimeString(),
                'updated_at'    =>Carbon::now()->toDateTimeString(),
            ],
        ];
        DB::table('blanks')->insert($blanks);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('blanks')->truncate();
    } 

}
